"""removed legacy details field, adds issuer and name fields

Revision ID: 3a0ccd2a4db9
Revises: 220d0e6a4bc0
Create Date: 2026-01-19 18:08:17.909428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a0ccd2a4db9'
down_revision: Union[str, Sequence[str], None] = '220d0e6a4bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grants', sa.Column('issuer', sa.Text(), nullable=True))
    op.alter_column('grants', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('grants', 'details')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grants', sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('grants', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('grants', 'issuer')
    # ### end Alembic commands ###
