"""create tables

Revision ID: 908e26cc1201
Revises:
Create Date: 2026-01-16 10:07:37.628005

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "908e26cc1201"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grants",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("button_text", sa.String(), nullable=True),
        sa.Column("card_body_text", sa.Text(), nullable=True),
        sa.Column("card_body_html", sa.Text(), nullable=True),
        sa.Column("links", postgresql.ARRAY(sa.String()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "organisations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("mission_and_focus", sa.Text(), nullable=False),
        sa.Column("about_us", sa.Text(), nullable=False),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "initiatives",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("goals", sa.Text(), nullable=False),
        sa.Column("audience", sa.String(), nullable=False),
        sa.Column("costs", sa.BigInteger(), nullable=True),
        sa.Column("stage", sa.String(), nullable=False),
        sa.Column("demographic", sa.String(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "results",
        sa.Column("grant_id", sa.Integer(), nullable=False),
        sa.Column("initiative_id", sa.Integer(), nullable=False),
        sa.Column("prelim_rating", sa.Integer(), nullable=False),
        sa.Column("grant_description", sa.Text(), nullable=True),
        sa.Column("criteria", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("grant_amount", sa.String(), nullable=True),
        sa.Column("match_rating", sa.Integer(), nullable=True),
        sa.Column("uncertainty_rating", sa.Integer(), nullable=True),
        sa.Column("deadline", sa.DateTime(), nullable=True),
        sa.Column("sources", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("sponsor_name", sa.String(), nullable=True),
        sa.Column("sponsor_description", sa.Text(), nullable=True),
        sa.Column("explanations", sa.JSON(), nullable=True),
        sa.CheckConstraint(
            "match_rating >= 0 AND match_rating <= 100", name="check_match_rating"
        ),
        sa.CheckConstraint(
            "prelim_rating >= 0 AND prelim_rating <= 100", name="check_prelim_rating"
        ),
        sa.CheckConstraint(
            "uncertainty_rating >= 0 AND uncertainty_rating <= 100",
            name="check_uncertainty_rating",
        ),
        sa.ForeignKeyConstraint(
            ["grant_id"],
            ["grants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["initiative_id"],
            ["initiatives.id"],
        ),
        sa.PrimaryKeyConstraint("grant_id", "initiative_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("results")
    op.drop_table("initiatives")
    op.drop_table("organisations")
    op.drop_table("grants")
    # ### end Alembic commands ###
